@startuml

actor "User" as actor
node "Backend-Restfull" {
    component "Controller" as controller
    component "Service" as service
    component "Repository" as repository
}
database "Mysql" as database

user <--> controller
controller <--> service
service <--> repository
repository <--> database

@enduml