# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url = jdbc:mysql://localhost:3306/gospring?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = jkt19S_*
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL8Dialect # Or MySQL5Dialect, depending on your MySQL version

## Hibernate Properties

## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update


#Flyway properties
#spring.flyway.enabled=true
#spring.flyway.url=jdbc:mysql://localhost:3306/gospring
#spring.flyway.user= root
#spring.flyway.password= jkt19S_*
#spring.flyway.locations=classpath:db/migration/mysql

# Jwt config
jwt.secret=YM/ABV0Wd4u72HpAONXgMj0D8V2KQ5IphKMiGlHEfv/kb65yD/e7eqCVkDUAi2s1Sw78pnPprvTzNSk/0Ua1AA==
jwt.expiration=3600000
jwt.refreshExpiration = 2700000
# Example: 1 hour in milliseconds

logging.level.org.springframework.security=DEBUG